[package]
name = "RlwyNetSim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.2"
egui = "0.21.0"
eframe = "0.21.3"
bevy = "0.10"
bevy_egui = "0.20"